export const SET_ALERT = "SET_ALERT";
export const SET_ALERT_SAGA = "SET_ALERT_SAGA";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REMOVE_ALERT_SAGA = "REMOVE_ALERT_SAGA";
export const REGISTER_SAGA = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
